### PR TITLE
setup: add automatic dependency resolution

### PR DESCRIPTION
**Pull request by pathfinder49**
as per title

### CODE REVIEW

**Comment by hartytp** [comment]
meh...I don't know how I feel about this. For such a simple package with essentially no dependencies (and, arguably, a design goal here should be to have strictly no dependencies beyond `numpy` in the core package). I'm not sure how worthwhile this is.

IIRC currently some of the test code imports a wigner package which I was playing around with (I check that my code gives the same answers as that package but much faster). I would not want that to blindly become a dependency for the entire ion phys package (maybe the real solution there is to remove that code now it's not really used any more and has probably bit rotted).

So, I'd say I'm open to being convinced that this is the correct thing to do, but am not there yet.

**Comment by dnadlinger** [comment]
What does this even do?

**Comment by pathfinder49** [comment]
This should help inform pip/setup.py which dependencies should be installed when installing ion_phys.

**Comment by dnadlinger** [comment]
I thought `packages` just lists packages to be distributed/installed?

**Comment by pathfinder49** [comment]
You are correct. Dependiencies should be specified via the `requires` keyword argument.

**Pull request closed without merging**
